language: python
python:
  - "2.7"
services: mysql
# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - mysql -e 'create database app_analytics;'
  - cd myapp; alembic upgrade head; cd ..

# command to run tests
script: #nosetests
  - python test.py --mysql=travis:''@localhost --port=5000