language: python
python:
  - "2.7"
services: mysql
# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - mysql -e 'create database app_analytics;'
  - cp -f build/alembic-travis.ini myapp/alembic.ini
  - cd myapp; alembic upgrade head

# command to run tests
script: nosetests