"""add flask security

Revision ID: 1784593c102f
Revises: 1c02a7117955
Create Date: 2013-09-01 15:38:34.098000

"""

# revision identifiers, used by Alembic.
revision = '1784593c102f'
down_revision = '1c02a7117955'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'active')
    ### end Alembic commands ###
