"""change column name in weibolist

Revision ID: 1aa6c4cc3c18
Revises: 1e6dd865048
Create Date: 2014-03-02 11:49:24.881000

"""

# revision identifiers, used by Alembic.
revision = '1aa6c4cc3c18'
down_revision = '1e6dd865048'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo_list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('weibo_list', u'create_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo_list', sa.Column(u'create_at', mysql.DATETIME(), nullable=True))
    op.drop_column('weibo_list', 'created_at')
    ### end Alembic commands ###
