"""change calendar table from DateTime to Date

Revision ID: 20fbc9f75bc6
Revises: 360b2c928597
Create Date: 2014-03-02 23:32:36.832000

"""

# revision identifiers, used by Alembic.
revision = '20fbc9f75bc6'
down_revision = '360b2c928597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
