"""change table weibo_list string to text

Revision ID: 3266bd42f92b
Revises: 52eb91132cc4
Create Date: 2013-09-14 18:44:01.322000

"""

# revision identifiers, used by Alembic.
revision = '3266bd42f92b'
down_revision = '52eb91132cc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weibo_list',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('user_uid', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status_type', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('original_pic', sa.Text(), nullable=True),
    sa.Column('bmiddle_pic', sa.Text(), nullable=True),
    sa.Column('thumbnail_pic', sa.Text(), nullable=True),
    sa.Column('geo', sa.Text(), nullable=True),
    sa.Column('retweeted_status', sa.Text(), nullable=True),
    sa.Column('reposts_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('attitudes_count', sa.Integer(), nullable=True),
    sa.Column('visible_type', sa.Integer(), nullable=True),
    sa.Column('pic_urls', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_id'),
    sa.UniqueConstraint('uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weibo_list')
    ### end Alembic commands ###
