"""add roles relationship

Revision ID: 35a9a74ee954
Revises: 3582dc71cce4
Create Date: 2013-09-01 21:02:50.477000

"""

# revision identifiers, used by Alembic.
revision = '35a9a74ee954'
down_revision = '3582dc71cce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
