"""create calendar table

Revision ID: 360b2c928597
Revises: 1aa6c4cc3c18
Create Date: 2014-03-02 23:13:11.934000

"""

# revision identifiers, used by Alembic.
revision = '360b2c928597'
down_revision = '1aa6c4cc3c18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    ### end Alembic commands ###
