"""add login time

Revision ID: 52eb91132cc4
Revises: 35a9a74ee954
Create Date: 2013-09-14 17:31:01.328000

"""

# revision identifiers, used by Alembic.
revision = '52eb91132cc4'
down_revision = '35a9a74ee954'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_time')
    ### end Alembic commands ###
